### PR TITLE
Add support of multiple rules

### PR DESCRIPTION
**Pull request by kenjis**
Now we have only one rule (last rule) to one field. This PR makes it possible to have multiple rules.

### CODE REVIEW

**Comment by harikt** [comment]
Aura.Input is not the final filtering . See earlier issues for #11, #13 , #31 for the same. So I am sorry, I don't think this will get merged :( .

**Comment by kenjis** [comment]
Thank you for your comment.
Oh I'm sorry. #31 is the exactly same as this.

I saw the issues. In my understanding:
- This filter is simple one.
- setRule() is not addRule(), so should not add rules.
- Multiple rules per one field increases complexity.
- You guys think there should be one rule per one field.

Right?

**Comment by harikt** [comment]
@kenjis actually Aura.Input promote the usage of Aura.Filter or any standalone library than adding rules.

> setRule() is not addRule(), so should not add rules.

set means reset all . Add means add more to the added ones. This applies to all the set and add functionality in @auraphp .

> Multiple rules per one field increases complexity. 

As I said, promotes the usage of Aura.Filter or any other standalone ones if you need more complex rules. As you know you can add custom rules in `aura/filter` .

**Comment by kenjis** [comment]
Thank you for your explanation.
I'll see Aura.Filter.

By the way, I send a PR with another approach to show multiple error messages: #40

**Comment by pmjones** [comment]
Hi @kenjis -- sorry to decline this one. I think you understand why already given your comment above; let me know if this is still a problem for you.

**Pull request closed without merging**
